Tensors are the fundamental data structure in PyTorch. They are multidimensional arrays similar to NumPy arrays, but with the added benefits of GPU acceleration and automatic differentiation.

In the examples below, we will explore how PyTorch tensors compare to NumPy arrays.

In [1]:
import numpy as np
import torch

We will demonstrate how to create NumPy arrays and PyTorch tensors using various methods.

In [7]:
#create a 1-d numpy array and 1-d torch tensor
a1 = np.array([1, 2, 3])
b1 = torch.tensor([1, 2, 3])
print(f'a1: {a1}')
print(f'b1: {b1}')

#create a 2-d numpy array and 2-d torch tensor
a2 = np.array([[1, 2], [3, 4]])
b2 = torch.tensor([[1, 2], [3, 4]])
print(f'a2:\n{a2}')
print(f'b2:\n{b2}')

#a matrix with normal values
a3 = np.random.normal(0, 1, (2, 3))
b3 = torch.randn(2, 3)
print(f'a3:\n{a3}')
print(f'b3:\n{b3}')

#zeros
a4 = np.zeros((2, 3))
b4 = torch.zeros(2, 3)
print(f'a4:\n{a4}')
print(f'b4:\n{b4}')

#ones
a5 = np.ones((2, 3))
b5 = torch.ones(2, 3)
print(f'a5:\n{a5}')
print(f'b5:\n{b5}')

a1: [1 2 3]
b1: tensor([1, 2, 3])
a2:
[[1 2]
 [3 4]]
b2:
tensor([[1, 2],
        [3, 4]])
a3:
[[ 0.12846842 -0.93910966 -0.04931906]
 [ 0.9343903   0.873301    1.57578625]]
b3:
tensor([[ 0.0200, -0.7921,  2.0591],
        [ 1.5203,  1.0524, -1.0650]])
a4:
[[0. 0. 0.]
 [0. 0. 0.]]
b4:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
a5:
[[1. 1. 1.]
 [1. 1. 1.]]
b5:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


We use a3, a4 and b3, b4 to demonstrate operations

In [12]:
print(f'NumPy Addition: \n {a3+a4}')
print(f'Torch Addition: \n {b3+b4}')

print(f'Numpy Element-wise Multiplication: \n {a3*a4}')
print(f'Torch Element-wise Multiplication: \n {b3*b4}')

print(f'NumPy Matrix Multiplication: \n {a3 @ a4.T}')
print(f'Torch Matrix Multiplication: \n {b3 @ b4.T}')

NumPy Addition: 
 [[ 0.12846842 -0.93910966 -0.04931906]
 [ 0.9343903   0.873301    1.57578625]]
Torch Addition: 
 tensor([[ 0.0200, -0.7921,  2.0591],
        [ 1.5203,  1.0524, -1.0650]])
Numpy Element-wise Multiplication: 
 [[ 0. -0. -0.]
 [ 0.  0.  0.]]
Torch Element-wise Multiplication: 
 tensor([[0., -0., 0.],
        [0., 0., -0.]])
NumPy Matrix Multiplication: 
 [[0. 0.]
 [0. 0.]]
Torch Matrix Multiplication: 
 tensor([[0., 0.],
        [0., 0.]])


Next, we will learn some other things, like how to convert a NumPy array to Torch Tensor, and how to reshape a tensor.

In [16]:
# convert a1 to a torch tensor
b1_from_a1 = torch.from_numpy(a1)
print(f'b1_from_a1: \n {b1_from_a1}')

# convert b1 to a numpy array
a1_from_b1 = b1.numpy()
print(f'a1_from_b1: \n {a1_from_b1}')

# reshape a1 to (3, 1) and convert to torch tensor
print(f'shape of b1: {b1.shape}')
b1_reshaped = b1.reshape(3, 1)
print(f'shape of b1_reshaped: {b1_reshaped.shape}')
print(f'b1_reshaped:\n{b1_reshaped}')

b1_from_a1: 
 tensor([1, 2, 3])
a1_from_b1: 
 [1 2 3]
shape of b1: torch.Size([3])
shape of b1_reshaped: torch.Size([3, 1])
b1_reshaped:
tensor([[1],
        [2],
        [3]])
